name: Lint

on:
  workflow_call:

jobs:
  clang-format:
    name: check ${{ matrix.path['check'] }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        path:
          - check: "include"
            exclude: "(rad\\.hpp)"
          - check: "src"
            exclude: ""
          - check: "test"
            exclude: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "18"
          check-path: ${{ matrix.path['check'] }}

  python-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python dependencies
        shell: bash
        run: |
          uv sync --locked

      - name: Ruff
        shell: bash
        run: ruff check tools

      - name: Mypy
        shell: bash
        run: mypy tools
